[package]
name = "puccinia"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
notify-rust = "4.9.0"
dbus = { version = "0.9.7" }
dbus-crossroads = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
